image: maven:3.9.6-eclipse-temurin-21

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - docker

# Step 1: Compila e crea il .jar
compile:
  stage: build
  script:
    - mvn clean package -DskipTests

# Step 2: Costruisci e fai push dell'immagine Docker
docker_build:
  image: docker:latest
  stage: docker
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - compile
